package org.xwiki.contrib.cli.sync;

import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.WatchEvent;
import java.nio.file.WatchKey;
import java.nio.file.WatchService;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

import org.xwiki.contrib.cli.Command;
import org.xwiki.contrib.cli.DocException;
import org.xwiki.contrib.cli.sync.event.AbstractEvent;

import static java.nio.file.StandardWatchEventKinds.ENTRY_CREATE;
import static java.nio.file.StandardWatchEventKinds.ENTRY_DELETE;
import static java.nio.file.StandardWatchEventKinds.ENTRY_MODIFY;
import static java.nio.file.StandardWatchEventKinds.OVERFLOW;

public abstract class AbstractFileSynchronizer extends AbstractSynchronizer implements PagesSynchronizer
{
    private final Map<Path, Long> fileChangedByMyself = new HashMap<>();

    public abstract List<AbstractEvent> getEvent(Path path, WatchEvent.Kind<?> kind) throws IOException, DocException;

    public abstract Path getPathToMonitor();

    protected AbstractFileSynchronizer(Command cmd, MemoryDocumentManager memoryDocumentManager)
    {
        super(cmd,  memoryDocumentManager);
    }

    @Override
    public void startNotifier(Consumer<AbstractEvent> callback)
    {
        WatchService watcher;
        WatchKey key;
        Map<WatchKey, Path> keyMaps = new HashMap<>();
        try {
            watcher = FileSystems.getDefault().newWatchService();
            watchDir(keyMaps, getPathToMonitor(), watcher);
        } catch (IOException e) {
            logger.error("Can't watch dir", e);
            return;
        }

        while (true) {
            // wait for key to be signaled
            try {
                key = watcher.take();
            } catch (InterruptedException x) {
                return;
            }

            for (WatchEvent<?> event : key.pollEvents()) {
                WatchEvent.Kind<?> kind = event.kind();
                var occurredTimestamp = System.currentTimeMillis();

                // This key is registered only
                // for ENTRY_CREATE events,
                // but an OVERFLOW event can
                // occur regardless if events
                // are lost or discarded.
                if (kind == OVERFLOW) {
                    continue;
                }

                // The filename is the
                // context of the event.
                WatchEvent<Path> ev = (WatchEvent<Path>) event;
                Path filename = ev.context();

                // Verify that the new
                //  file is a text file.
                // Resolve the filename against the directory.
                // If the filename is "test" and the directory is "foo",
                // the resolved name is "test/foo".
                Path child = keyMaps.get(key).resolve(filename);

                if (child.toString().endsWith("~") || child.toString().endsWith(".swp")) {
                    logger.debug("Ignoring temporary file generated by editors");
                    continue;
                }
                if (Files.isDirectory(child)) {
                    logger.debug("Ignoring directory");
                    continue;
                }

                // Ignore event triggerd by itself
                var selfEditTimestamps = fileChangedByMyself.getOrDefault(child, 0L);
                if (occurredTimestamp < selfEditTimestamps + 100) {
                    continue;
                }

                List<AbstractEvent> events = List.of();
                try {
                    events = getEvent(child, kind);
                } catch (IOException | DocException e) {
                    logger.error("Error while processing event for path [{}]", child, e);
                }
                for (var e : events) {
                    callback.accept(e);
                }
            }

            // Reset the key -- this step is critical if you want to
            // receive further watch events.  If the key is no longer valid,
            // the directory is inaccessible so exit the loop.
            boolean valid = key.reset();
            if (!valid) {
                break;
            }
        }
        logger.debug("Ending watch loop");
    }

    protected void writeInFileOnlyIfChanged(Path path, String value) throws IOException
    {
        if (!Files.exists(path) || !Files.readString(path).strip().equals(value.strip())) {
            markFileAsEdited(path);
            Files.writeString(path, value);
        }
    }

    protected void markFileAsEdited(Path path)
    {
        fileChangedByMyself.put(path, System.currentTimeMillis());
    }

    private void watchDir(Map<WatchKey, Path> keyMaps, Path path, WatchService watcher) throws IOException
    {
        keyMaps.put(path.register(watcher,
            ENTRY_CREATE,
            ENTRY_DELETE,
            ENTRY_MODIFY), path);
        try (var dirList = Files.list(path)) {
            for (var d : dirList.filter(Files::isDirectory).toList()) {
                watchDir(keyMaps, d, watcher);
            }
        }
    }
}
